name: uCars
main: com.useful.ucars.ucars
version: 10
softdepend: [Vault]
depend: [ProtocolLib]
commands:
   ucars:
        description: This gives ucars info
        usage: /<command>
        permission: ucars.ucars
        permission-message: You don't have access to this command
        default: true
   reloaducars:
        description: This reloads the config
        usage: /<command>
        permission: ucars.reloaducars
        permission-message: You don't have access to this command
        default: op
   ufuel:
        description: This buys the specified amount of ufuel
        usage: /<command> [Buy <Amount>], [View]
        permission: ucars.ucars
        permission-message: You don't have access to this command
        default: true
   cars:
        description: This allows for car management (remove etc...)
        usage: /<command> [Remove]
        permission: ucars.cars
        permission-message: You don't have access to this command
        default: op