name: uCars
main: com.useful.ucars.ucars
version: 1
commands:
   ucars:
        description: This gives ucars info
        usage: /<command>
        permission: ucars.ucars
        permission-message: You don't have access to this command
        default: true